[package]
name = "context-resolver-search"
version.workspace = true
edition.workspace = true

[dependencies]
context-resolver-core.workspace = true
syntax-helper-search.workspace = true

[dev-dependencies]
rusqlite.workspace = true
syntax-helper-language.workspace = true
syntax-helper-model.workspace = true
