[package]
name = "hbk-doc-site"
version.workspace = true
edition.workspace = true

[dependencies]
fnv.workspace = true
hbk-book.workspace = true
hbk-book-export.workspace = true
serde.workspace = true
serde_json.workspace = true
slug.workspace = true
thiserror.workspace = true

[dev-dependencies]
hbk-book = { workspace = true, features = ["test-utils"] }
